### ISSUE TITLE
Detect incompatibility and raise a relevant exception

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-client-nodejs#47]
## Problem to Solve

When there is an incompatibility between Client Node.js and the running Grakn Server, the exception thrown by the client seems unrelated to the real cause of the problem. In fact, the error message may even be incorrect, given that the keyspace does exist with the given name.

## Current Workaround

If encountering this exception for the first time, only searching the web or asking the community can lead the user to the solution.

## Proposed Solution

Have Client Node.js to identify the incompatibility and throw an exception with a helpful message. e.g. `Client Node.js version 1.5.3 does not support the running Grakn Core server. Please refer to the documentation of client Node.js to ensure compatibility.`

## Additional Information

N/A

**Comment by vmax** [comment]
@sorsaffari (cc @haikalpribadi @lolski) as this feature seems to be needed for *all* clients, should we make a gRPC endpoint in server that would tell minimal version of client needed to connect to that server?

**Comment by flyingsilverfin** [comment]
@vmax  I was thinking each client would maintain a compatibility table rather than server maintaining one per client (since each client can have different versions). The server just needs to return its version when we open a client I think!
This would entail just having a new `version` endpoint that we check when opening a channel in each client would be the most general solution, what do you think?

**Comment by vmax** [comment]
@flyingsilverfin let me correct myself a bit. Server should report minimal version of _protocol_ that client should implement in order to connect to it.

Say, we establish that current version of protocol that latest server and client implement is `v1`.
Then, when we need to introduce incompatible changes in server, we'll have to bump server to report `v2` as the minimal protocol it supports — therefore, clients that only implement `v1` would be rejected a connection.

**Comment by haikalpribadi** [comment]
I agree with @vmax . It's a good idea for the server to report the protocol version it serves, and the client validates if they are using that protocol. It's has to be one to one anyways. cc: @sorsaffari @flyingsilverfin @lolski
